### ISSUE TITLE
terra-toolkit webpack.config issue

### ISSUE THREAD

**Issue by karnamanirudh** [cerner/terra-toolkit#150]
Error: Cannot find module 'terra-toolkit/config/webpack/webpack.config'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Project\asp and webpack-latest\develop_iteration8\eWorkBook\CernerEWBWeb\AspAndWebpack\webpack.config.js:5:32)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at requireConfig (C:\Project\asp and webpack-latest\develop_iteration8\eWorkBook\CernerEWBWeb\AspAndWebpack\node_modules\webpack\bin\convert-argv.js:97:18)
    at C:\Project\asp and webpack-latest\develop_iteration8\eWorkBook\CernerEWBWeb\AspAndWebpack\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports

**Comment by mjhenkes** [comment]
Please use our bug template and provide more details to log this issue.
