### ISSUE TITLE
tt-wdio cannot resolve path to default config file

### ISSUE THREAD

**Issue by dv297** [cerner/terra-toolkit#154]
# Bug Report

## Description
When running the command...
```
tt-wdio --locales ['en','en-GB','es'] --formFactors ['tiny','medium','large'] 
                                                                              
```

in an NPM script, I get the follow error log. Note the extra file path in the Error.

C:\FooProject/**C:\FooProject\node_modules\terra-dev-site\config\wdio\wdio.conf.js**

```
C:\FooProject
λ npm run test:wdio:locally

> scheduling-orion-sample-js@0.0.0 test:wdio:locally C:\FooProject
> tt-wdio --locales ['en','en-GB','es'] --formFactors ['tiny','medium','large']

module.js:545
    throw err;
    ^

Error: Cannot find module 'C:\FooProject/C:\FooProject\node_modules\terra-dev-site\config\wdio\wdio.conf.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at loadWdioConfig (C:\FooProject\node_modules\terra-toolkit\scripts\wdio\clean-screenshots.js:6:38)
    at cleanSnapshots (C:\FooProject\node_modules\terra-toolkit\scripts\wdio\clean-screenshots.js:15:22)
    at Object.<anonymous> (C:\FooProject\node_modules\terra-toolkit\scripts\wdio\wdio-runner-cli.js:43:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
```

## Steps to Reproduce

1. Run `tt-wdio --locales ['en','en-GB','es'] --formFactors ['tiny','medium','large']` as an NPM script

## Expected Behavior
WDIO tests run

## Possible Solution
This might be a Windows related problem. The stack trace mentioned clean-screenshots.js file. I noticed that when importing the path module, the "posix" variation was used. I thought this was curious, so I changed the line.
```diff
- const { posix: path } = require('path');
+ const path = require('path');
```

I was able to get a little further in the process, but stopped with error...

```
Module not found: Error: Can't resolve 'FooProject/lib/FooProject/components/FooView' in 'C:\FooProject\lib\terra-dev-site\test'
resolve 'FooProject/lib/FooProject/components/FooView' in 'C:\FooProject\lib\terra-dev-site\test'
  Parsed request is a module
  using description file: C:\FooProject\package.json (relative path: ./lib/terra-dev-site/test)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in C:\FooProject\dev-site-config
        using description file: C:\FooProject\package.json (relative path: ./dev-site-config)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\FooProject\package.json (relative path: ./dev-site-config/FooProject/lib/FooProject/components/FooView)
```

## Environment

* Component Name and Version:
* Node/npm Version: Node 9.8.0/ NPM 6.4.0
* Webpack Version: 4.16.5
* Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by dv297** [comment]
Handled in #156
