### ISSUE TITLE
Exit wdio test run if webpack fails to compile

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-toolkit#345]
# Feature Request

## Description
Exit wdio test run if webpack fails to compile. With the postcss issue webpack failed to compile but the test run hung. We should investigate failing wdio quickly when webpack fails to compile.

**Comment by nramamurth** [comment]
@mjhenkes @emilyrohrbough 

I wonder if we could leverage one of the webpack `compiler` hooks to achieve this: [`failed`](https://webpack.js.org/api/compiler-hooks/#failed). 

I quickly tested it out by simulating the scenario where the test run hung due to the postcss issue. This does seem to work but I obviously think it may need to be "bettered". 

Just for a quick test, I added the following hook to the [`TerraDevSite` plugin](https://github.com/cerner/terra-dev-site/blob/master/config/webpack/plugin/TerraDevSite.js#L59) but if this approach is something we want to leverage and if we do not want to tie it up with the `TerraDevSite` plugin, we may have to find a better spot. 

```
compiler.hooks.failed.tap('TerraDevSite', (
   error
 ) => {
   console.log(error.message || error);
   process.exit(1);
});
```

This is the output (with postcss issue as an example) ⬇️

<details> 
<summary> When <b>error.message</b> is printed. </summary>

```
➜  terra-core git:(master) ✗ npm run wdio

> terra-core@0.1.0 wdio /Users/nr046097/terra-core
> NODE_OPTIONS=--max-old-space-size=2048 wdio node_modules/terra-toolkit/config/wdio/wdio.conf.js


[Terra-Toolkit:terra-service] Running tests against Selenium 3.14
[terra-aggregate-translations] Aggregating translations for en,en-AU,en-CA,en-US,en-GB,es,es-US,es-ES,de,fr,fr-FR,nl,nl-BE,pt,pt-BR,sv,sv-SE locales.
ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /Users/nr046097/terra-core
ℹ ｢wds｣: 404s will fallback to /index.html
[Terra-Toolkit:serve-static-service] Server started listening
[Terra-Toolkit:selenium-docker] Removing docker selenium stack
[Terra-Toolkit:selenium-docker] Deploying docker selenium stack
[Terra-Toolkit:selenium-docker] Ensuring selenium status is ready
Cannot read property 'value' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terra-core@0.1.0 wdio: `NODE_OPTIONS=--max-old-space-size=2048 wdio node_modules/terra-toolkit/config/wdio/wdio.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terra-core@0.1.0 wdio script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nr046097/.npm/_logs/2019-11-04T10_13_14_314Z-debug.log
```

</details>

<details> 
<summary> When <b>error</b> is printed. </summary>

```
➜  terra-core git:(master) ✗ npm run wdio

> terra-core@0.1.0 wdio /Users/nr046097/terra-core
> NODE_OPTIONS=--max-old-space-size=2048 wdio node_modules/terra-toolkit/config/wdio/wdio.conf.js


[Terra-Toolkit:terra-service] Running tests against Selenium 3.14
[terra-aggregate-translations] Aggregating translations for en,en-AU,en-CA,en-US,en-GB,es,es-US,es-ES,de,fr,fr-FR,nl,nl-BE,pt,pt-BR,sv,sv-SE locales.
ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /Users/nr046097/terra-core
ℹ ｢wds｣: 404s will fallback to /index.html
[Terra-Toolkit:serve-static-service] Server started listening
[Terra-Toolkit:selenium-docker] Removing docker selenium stack
[Terra-Toolkit:selenium-docker] Deploying docker selenium stack
[Terra-Toolkit:selenium-docker] Ensuring selenium status is ready
{ TypeError: Cannot read property 'value' of undefined
    at /Users/nr046097/terra-core/5-649b82ff95cd58e84e4d.css:7:11962
    at new Quoted (/Users/nr046097/terra-core/node_modules/postcss-values-parser/lib/nodes/Quoted.js:19:28)
    at cloneNode (/Users/nr046097/terra-core/node_modules/postcss/lib/node.js:15:16)
    at Quoted.clone (/Users/nr046097/terra-core/node_modules/postcss/lib/node.js:248:18)
    at Func.Node (/Users/nr046097/terra-core/node_modules/postcss/lib/node.js:83:30)
    at new Container (/Users/nr046097/terra-core/node_modules/postcss/lib/container.js:45:18)
    at new Container (/Users/nr046097/terra-core/node_modules/postcss-values-parser/lib/nodes/Container.js:15:1)
    at new Func (/Users/nr046097/terra-core/node_modules/postcss-values-parser/lib/nodes/Func.js:19:5)
    at asClonedNode (/Users/nr046097/terra-core/node_modules/postcss-custom-properties/index.cjs.js:254:21)
    at array.map.node (/Users/nr046097/terra-core/node_modules/postcss-custom-properties/index.cjs.js:250:60)
    at Array.map (<anonymous>)
    at asClonedArray (/Users/nr046097/terra-core/node_modules/postcss-custom-properties/index.cjs.js:250:48)
    at asClonedArrayWithBeforeSpacing (/Users/nr046097/terra-core/node_modules/postcss-custom-properties/index.cjs.js:240:23)
    at root.nodes.slice.forEach.child (/Users/nr046097/terra-core/node_modules/postcss-custom-properties/index.cjs.js:213:44)
    at Array.forEach (<anonymous>)
    at transformValueAST (/Users/nr046097/terra-core/node_modules/postcss-custom-properties/index.cjs.js:193:24)
    at root.walkDecls.decl (/Users/nr046097/terra-core/node_modules/postcss-custom-properties/index.cjs.js:275:28)
  postcssNode:
   Declaration {
     raws: { before: '', between: ':' },
     type: 'decl',
     parent:
      Rule {
        raws: [Object],
        type: 'rule',
        nodes: [Array],
        parent: [Object],
        source: [Object],
        selector: '[dir] .SplitButton-module__neutral___1rYRo .SplitButton-module__caret-icon___2xV-Y',
        lastEach: 1,
        indexes: [Object] },
     source: { start: [Object], input: [Object], end: [Object] },
     prop: 'background-image',
     value: 'var(--terra-dropdown-button-caret-background-image-neutral, url("data:image/svg+xml;charset=US-ASCII,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2048%2048%22%20class%3D%22is-bidi%22%3E%3Cpath%20fill%3D%22%231c1f21%22%20d%3D%22M48%2012L24%2036%200%2012h48z%22%2F%3E%3C%2Fsvg%3E"))' } }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terra-core@0.1.0 wdio: `NODE_OPTIONS=--max-old-space-size=2048 wdio node_modules/terra-toolkit/config/wdio/wdio.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terra-core@0.1.0 wdio script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nr046097/.npm/_logs/2019-11-04T10_17_06_221Z-debug.log
```

</details>

The other alternative that I could think of is using webpack's [`bail`](https://webpack.js.org/configuration/other-options/#bail) option in the config but the process did not exit and does not seem to be respected at least in webpack 4. I also did see a couple of issues logged complaining about bail not working as expected ¯\_(ツ)_/¯

**Comment by emilyrohrbough** [comment]
I think you are on the right track on using the webpack compiler hook called failed. 👍 

I did a little prototyping, and we can add a hook in the TerraServeStaticService to tap into the failed hook to reject the promise. Something like:

```js
    compiler.hooks.failed.tap('killTestRun', function (stats) {
        Logger.warn('Webpack failed to compile', { context });
        reject();
    }); 
```

<details>
<summary>This returns:</summary>

```sh
[Terra-Toolkit:terra-service] Running tests against Selenium 3.14
[terra-aggregate-translations] Aggregating translations for en locales.
ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from 
ℹ ｢wds｣: Content not from webpack is served from /Users/er047227/orion/chart-summary/chart-summary-context
ℹ ｢wds｣: 404s will fallback to /index.html
[Terra-Toolkit:serve-static-service] Server started listening
[Terra-Toolkit:selenium-docker] Removing docker selenium stack
[Terra-Toolkit:selenium-docker] Deploying docker selenium stack
[Terra-Toolkit:selenium-docker] Ensuring selenium status is ready
[Terra-Toolkit:serve-static-service] Webpack failed to compile
✖ ｢wdm｣: TypeError: Cannot read property 'value' of undefined
    at /Users/er047227/orion/chart-summary/chart-summary-context/index-e5b1110e0737b3d63bd3.css:7:1233
    at new Quoted (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/postcss-values-parser/lib/nodes/Quoted.js:19:28)
    at cloneNode (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/postcss/lib/node.js:15:16)
    at Quoted.clone (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/postcss/lib/node.js:248:18)
    at Func.Node (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/postcss/lib/node.js:83:30)
    at new Container (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/postcss/lib/container.js:45:18)
    at new Container (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/postcss-values-parser/lib/nodes/Container.js:15:1)
    at new Func (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/postcss-values-parser/lib/nodes/Func.js:19:5)
    at asClonedNode (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/postcss-custom-properties/index.cjs.js:254:21)
    at array.map.node (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/postcss-custom-properties/index.cjs.js:250:60)
    at Array.map (<anonymous>)
    at asClonedArray (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/postcss-custom-properties/index.cjs.js:250:48)
    at asClonedArrayWithBeforeSpacing (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/postcss-custom-properties/index.cjs.js:240:23)
    at root.nodes.slice.forEach.child (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/postcss-custom-properties/index.cjs.js:213:44)
    at Array.forEach (<anonymous>)
    at transformValueAST (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/postcss-custom-properties/index.cjs.js:193:24)
    at root.walkDecls.decl (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/postcss-custom-properties/index.cjs.js:275:28)
/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/webdriverio/build/lib/cli.js:457
                throw e;
                ^

TypeError: Cannot read property 'stack' of undefined
    at Launcher._callee2$ (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/webdriverio/build/lib/launcher.js:417:107)
    at tryCatch (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as throw] (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/er047227/orion/chart-summary/chart-summary-context/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/er047227/orion/chart-summary/chart-summary-context/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

</details>

[We already tap into the done hook to check for errors](https://github.com/cerner/terra-toolkit/blob/master/src/wdio/services/ServeStaticService.js#L69). I think the reason we are seeing the failure is we aren't making it to the done hook.

**Comment by nramamurth** [comment]
@emilyrohrbough Awesome. That makes sense, thank you. 

I am curious, what is the order of execution here? I notice that the compiler hook within `TerraDevSite` plugin hits before this is hit when I tested.

**Comment by emilyrohrbough** [comment]
Not knowing much on the topic, I would assume the TerraDevSite Plugin will hit these tabable hooks before the compiler will hit these hooks. My thought is since the TerraDevSite plugin ran run to compile the assets, and if a failure occurs, technically the plugin will have access to the error before the overall compilation marks itself as failed.
