### ISSUE TITLE
[terra-functional-testing] Wait for the browser to become available for all browsers

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-toolkit#615]
# Feature Request

## Description

As a developer I want to wait for the browser to become available before executing any browser commands. 

We'll know we are done when the Terra service before hook waits for the browser to become available before running browser commands. Specifically the setViewport command.

## Additional Context / Screenshots

Note: The errors referenced below are occurring on terra-toolkit using WebDriverIO v4, but we should anticipate using the same safe guards and logging in the terra-functional-testing project.

A few teams are experiencing frequent BROWSER_TIMEOUT errors in Chrome when the before hook invokes the [setViewportSize command](https://github.com/cerner/terra-toolkit/blob/6c13f6f50f47a2d92a29aa744a25591c3e19d312/packages/terra-functional-testing/src/services/wdio-terra-service.js#L99).

A possible solution is to use the waitFor for all browsers and not do the specific browser check:

https://github.com/cerner/terra-toolkit/blob/6c13f6f50f47a2d92a29aa744a25591c3e19d312/packages/terra-functional-testing/src/services/wdio-terra-service.js#L91-L96

Stack trace:

```
Error: A session is either terminated or not started

    at windowHandleSize([object Object]) - setViewportSize.js:83:26

FERROR: Session [e9dfca5689c81e4ebd82c86354115eaf] was terminated due to BROWSER_TIMEOUT

chrome

    at new RuntimeError (/app/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)

    at Request._callback (/app/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)

    at Request.self.callback (/app/node_modules/request/request.js:185:22)

    at Request.emit (events.js:198:13)

    at Request.EventEmitter.emit (domain.js:448:20)

    at Request.<anonymous> (/app/node_modules/request/request.js:1154:10)

    at Request.emit (events.js:198:13)

    at Request.EventEmitter.emit (domain.js:448:20)

    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1076:12)

    at Object.onceWrapper (events.js:286:20)

    at IncomingMessage.emit (events.js:203:15)

    at IncomingMessage.EventEmitter.emit (domain.js:448:20)

    at endReadableNT (_stream_readable.js:1145:12)

    at process._tickCallback (internal/process/next_tick.js:63:19)

ERROR: Session [e9dfca5689c81e4ebd82c86354115eaf] was terminated due to BROWSER_TIMEOUT



    at new RuntimeError (/app/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)

    at Request._callback (/app/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)

    at Request.self.callback (/app/node_modules/request/request.js:185:22)

    at Request.emit (events.js:198:13)

    at Request.EventEmitter.emit (domain.js:448:20)

    at Request.<anonymous> (/app/node_modules/request/request.js:1154:10)

    at Request.emit (events.js:198:13)

    at Request.EventEmitter.emit (domain.js:448:20)

    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1076:12)

    at Object.onceWrapper (events.js:286:20)

    at IncomingMessage.emit (events.js:203:15)

    at IncomingMessage.EventEmitter.emit (domain.js:448:20)

    at endReadableNT (_stream_readable.js:1145:12)

    at process._tickCallback (internal/process/next_tick.js:63:19)

Error: A session is either terminated or not started

    at windowHandleSize() - setViewportSize.js:72:17

Error: An unknown server-side error occurred while processing the command.

    at windowHandleSize() - setViewportSize.js:72:17
```

**Comment by StephenEsser** [comment]
Issue logged to terra-toolkit:

https://github.com/cerner/terra-toolkit-boneyard/issues/91
