### ISSUE TITLE
Cannot Run wdio Tests on Windows Machine

### ISSUE THREAD

**Issue by k1nger** [cerner/terra-toolkit#62]
# Issue Description
Selenium fails to start and the test don't execute. This seems to only be occurring on Windows 10 machines as far as I've tested. Successfully started and ran on colleagues with macbook and on our jenkins server. Most of my team are .NET developers and need windows machines. I've also tried using the Ubuntu Subsystem for Windows feature on win 10 but also get the same error.

I've tried changing some parameters in the docker-compose file without success and tried to resolve it using some findings on Google but haven't had success yet. This is happening not only with my repository, but it is also happening with terra-toolkit as well. I cloned the terra-toolkit repo and tried running WDIO tests and received the same result.

This leads me to believe it' something potentially with the container, or docker on windows.

The error:
```
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.9.11}, rotatable: true}
chrome
    at new RuntimeError (c:\Development\singlestack\terra-toolkit\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (c:\Development\singlestack\terra-toolkit\node_modules\webdriverio\build\lib\utils\RequestHandler.js:313:39)
    at Request.self.callback (c:\Development\singlestack\terra-toolkit\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (c:\Development\singlestack\terra-toolkit\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (c:\Development\singlestack\terra-toolkit\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior
Selenium should start and execute the tests

## Current Behavior
Selenium fails with the error above.

## Steps to Reproduce
1. Execute npm run wdio using the docker-compose file provided by terra-toolkit on a windows 10 machine.

## Environment
* Component Version: Latest terra-toolkit
* Operating System and version: Windows 10 Enterprise Edition 1703
* Versions of tools:
** Docker version 17.12.0-ce, build c97c6d6,
** Node version: v8.4.0,
** NPM version: 5.3.0.

**Comment by mjhenkes** [comment]
@k1nger could you try checking out and running tests on one of our already setup repos? Ideally we could then eliminate terra-toolkit setup issues with your repo.
You could try terra-framework. Core takes forever to test. github.com/cerner/terra-framework

**Comment by k1nger** [comment]
Yes, I mentioned in the issue description I've tried running the terra-toolkit wdio test and received the same failure. I'll try terra-framework as well.

**Comment by k1nger** [comment]
Same error on both terra-toolkit and terra-framework. Tested on both my machine and a colleages machine running windows 10 1703. 



<details not-open>
<summary>Full output:</summary>


<pre><code>C:\Development\singlestack\terra-framework>npm run wdio

> terra-framework@0.1.0 wdio C:\Development\singlestack\terra-framework
> wdio


[WebDevService] Starting WebpackDevServer
[SeleniumDocker] Deploying docker selenium stack
[WebDevService] Webpack compiled successfully
[SeleniumDocker] Ensuring selenium status is ready
A service failed in the 'onPrepare' hook
undefined

Continue...
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.9.9}, rotatable: true}
chrome
    at new RuntimeError (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\RequestHandler.js:313:39)
    at Request.self.callback (C:\Development\singlestack\terra-framework\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.9.9}, rotatable: true}
chrome
    at new RuntimeError (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\RequestHandler.js:313:39)
    at Request.self.callback (C:\Development\singlestack\terra-framework\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.9.9}, rotatable: true}
chrome
    at new RuntimeError (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\RequestHandler.js:313:39)
    at Request.self.callback (C:\Development\singlestack\terra-framework\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.9.9}, rotatable: true}
chrome
    at new RuntimeError (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\RequestHandler.js:313:39)
    at Request.self.callback (C:\Development\singlestack\terra-framework\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.9.9}, rotatable: true}
chrome
    at new RuntimeError (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\RequestHandler.js:313:39)
    at Request.self.callback (C:\Development\singlestack\terra-framework\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.9.9}, rotatable: true}
chrome
    at new RuntimeError (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\RequestHandler.js:313:39)
    at Request.self.callback (C:\Development\singlestack\terra-framework\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.9.9}, rotatable: true}
chrome
    at new RuntimeError (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\RequestHandler.js:313:39)
    at Request.self.callback (C:\Development\singlestack\terra-framework\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.9.9}, rotatable: true}
chrome
    at new RuntimeError (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\RequestHandler.js:313:39)
    at Request.self.callback (C:\Development\singlestack\terra-framework\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.9.9}, rotatable: true}
chrome
    at new RuntimeError (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\RequestHandler.js:313:39)
    at Request.self.callback (C:\Development\singlestack\terra-framework\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.9.9}, rotatable: true}
chrome
    at new RuntimeError (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (C:\Development\singlestack\terra-framework\node_modules\webdriverio\build\lib\utils\RequestHandler.js:313:39)
    at Request.self.callback (C:\Development\singlestack\terra-framework\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Development\singlestack\terra-framework\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

[SeleniumDocker] Removing docker selenium stack
[WebDevService] Closing WebpackDevServer
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terra-framework@0.1.0 wdio: `wdio`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terra-framework@0.1.0 wdio script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rk039267\AppData\Roaming\npm-cache\_logs\2018-03-02T08_06_22_210Z-debug.log</code></pre>
</details>

**Comment by bjankord** [comment]
I've hit this error recently as well.

 

<details not-open>
<summary>Here's the error message I'm seeing.</summary>


<pre><code>
terra-action-header|terra-action-header⚡ ⇒ npm run test:wdio

> terra-action-header@0.0.0 test:wdio /Users/bj031910/repos/terra-core/packages/terra-action-header
> wdio ../../wdio.conf.js


[ExpresDevService] Webpack compilation started
[SeleniumDocker] Deploying docker selenium stack
[SeleniumDocker] Ensuring selenium status is ready
[ExpresDevService] Webpack compiled successfully
[ExpresDevService] Express server started
A service failed in the 'onPrepare' hook
undefined

Continue...
ERROR: Error forwarding the new session Empty pool of VM for setup Capabilities {browserName: chrome, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.9.9}, rotatable: true}
chrome
    at new RuntimeError (/Users/bj031910/repos/terra-core/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (/Users/bj031910/repos/terra-core/node_modules/webdriverio/build/lib/utils/RequestHandler.js:313:39)
    at Request.self.callback (/Users/bj031910/repos/terra-core/node_modules/webdriverio/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/webdriverio/node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/bj031910/repos/terra-core/node_modules/webdriverio/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

[SeleniumDocker] Removing docker selenium stack
[ExpresDevService] Closing WebpackDevServer
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terra-action-header@0.0.0 test:wdio: `wdio ../../wdio.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terra-action-header@0.0.0 test:wdio script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
</code></pre>
</details>

<br>
<p>Just before getting this error, I had tried running wdio tests and received the following error. I'm able to get rid of the above error by removing all my docker data via docker for mac and then I'm left with the error below.</p>

<img src="https://image.ibb.co/c6hqjx/Screen_Shot_2018_04_08_at_5_19_37_AM.png">

```
// Appreviated error message
terra-action-header|terra-action-header ⇒ npm run test:wdio

> terra-action-header@0.0.0 test:wdio /Users/bj031910/repos/terra-core/packages/terra-action-header
> wdio ../../wdio.conf.js


[ExpresDevService] Webpack compilation started
[SeleniumDocker] Initializing docker swarm
[SeleniumDocker] Deploying docker selenium stack
[SeleniumDocker] Ensuring selenium status is ready
[ExpresDevService] Webpack compiled successfully
[ExpresDevService] Express server started
A service failed in the 'onPrepare' hook
undefined

Continue...
ERROR: connect ECONNREFUSED 127.0.0.1:4444
chrome
```

<details not-open>
<summary>Full Error message</summary>


<pre><code>
terra-action-header|terra-action-header⚡ ⇒ npm run test:wdio

> terra-action-header@0.0.0 test:wdio /Users/bj031910/repos/terra-core/packages/terra-action-header
> wdio ../../wdio.conf.js


[ExpresDevService] Webpack compilation started
[SeleniumDocker] Initializing docker swarm
[SeleniumDocker] Deploying docker selenium stack
[SeleniumDocker] Ensuring selenium status is ready
[ExpresDevService] Webpack compiled successfully
[ExpresDevService] Express server started
A service failed in the 'onPrepare' hook
undefined

Continue...
ERROR: connect ECONNREFUSED 127.0.0.1:4444
chrome
    at new RuntimeError (/Users/bj031910/repos/terra-core/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (/Users/bj031910/repos/terra-core/node_modules/webdriverio/build/lib/utils/RequestHandler.js:327:43)
    at self.callback (/Users/bj031910/repos/terra-core/node_modules/webdriverio/node_modules/request/request.js:186:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestError (/Users/bj031910/repos/terra-core/node_modules/webdriverio/node_modules/request/request.js:878:8)
    at emitOne (events.js:120:20)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

[SeleniumDocker] Removing docker selenium stack
[ExpresDevService] Closing WebpackDevServer
</code></pre>
</details>

**Comment by SharathAlur** [comment]
Even after changing the chrome version to 3.11 in the local docker-compose.yml file, I am facing the same error.

The error is:

> [SeleniumDocker] Deploying docker selenium stack
> [WebDevService] Webpack compiled successfully
> [WebDevService] Webpack compiled unsuccessfully
> [WebDevService] Webpack compiled successfully
> [SeleniumDocker] Ensuring selenium status is ready
> A service failed in the 'onPrepare' hook
> undefined
> 
> Continue...
> ERROR: connect ECONNREFUSED 127.0.0.1:4444
> chrome
>     at new RuntimeError (/Users/sm029549/GitHub/orion-inventory-views-js/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
>     at Request._callback (/Users/sm029549/GitHub/orion-inventory-views-js/node_modules/webdriverio/build/lib/utils/RequestHandler.js:330:43)
>     at self.callback (/Users/sm029549/GitHub/orion-inventory-views-js/node_modules/webdriverio/node_modules/request/request.js:186:22)
>     at emitOne (events.js:116:13)
>     at Request.emit (events.js:211:7)
>     at Request.onRequestError (/Users/sm029549/GitHub/orion-inventory-views-js/node_modules/webdriverio/node_modules/request/request.js:878:8)
>     at emitOne (events.js:121:20)
>     at ClientRequest.emit (events.js:211:7)
>     at Socket.socketErrorListener (_http_client.js:387:9)
>     at emitOne (events.js:116:13)
> 
> [SeleniumDocker] Removing docker selenium stack
> [WebDevService] Closing WebpackDevServer
> npm ERR! Test failed.  See above for more details.

**Comment by alex-bezek** [comment]
We used to get the ECONNREFUSED 127.0.0.1:4444 but didn't think it was related to this issue as the original comment/post had a different error message. We did notice that cleaning out all your  docker containers would sometimes cause this issue. Pre-pulling the chrome and selenium containers seemed to fix it for multiple people.

Some people wanted to add
```
const execSync = require('child_process').execSync;

console.log('Pulling Latest Selenium Image...');
execSync(`docker pull selenium/hub:latest`);

console.log('Pulling Latest Node Chrome Image...');
execSync(`docker pull selenium/node-chrome:3.8.1-erbium`);
```
as a pre-command in our repo, but we encouraged them to make a PR here if it fixed it. Let me know if this has any affect on your issue

**Comment by k1nger** [comment]
I seemed to get past the initial issue. But the testrunner is timing out now. To get past the initial issue (I don't know if this neccesarily helped fix it or not, but...) I followed along with the selenium documentation.

Before I started I ran a docker system prune -a --volumes

Then following along with the selenium documentation:


```
docker network create grid

docker run -d -p 4444:4444 --net grid --name selenium-hub selenium/hub:3.11.0-dysprosium

docker run -d --net grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm selenium/node-chrome:3.11.0-dysprosium
```


After that I edited the docker-compose file to use the 3.11.0-dysprosium version for selenium/hub and selenium/node-chrome. Now I'm just getting a ECONNRESET error:

```
C:\Development\tiff-viewer-js>npm run test:wdio

> tiff-viewer-js@0.0.1 test:wdio C:\Development\tiff-viewer-js
> wdio

[SeleniumDocker] Deploying docker selenium stack
[SeleniumDocker] Ensuring selenium status is ready
A service failed in the 'onPrepare' hook
undefined

Continue...
ERROR: read ECONNRESET
chrome
    at new RuntimeError (C:\Development\tiff-viewer-js\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:144:12)
    at Request._callback (C:\Development\tiff-viewer-js\node_modules\webdriverio\build\lib\utils\RequestHandler.js:330:43)
    at self.callback (C:\Development\tiff-viewer-js\node_modules\webdriverio\node_modules\request\request.js:186:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestError (C:\Development\tiff-viewer-js\node_modules\webdriverio\node_modules\request\request.js:878:8)
    at emitOne (events.js:120:20)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)

[SeleniumDocker] Removing docker selenium stack
```

**Comment by k1nger** [comment]
I also tried to minimize my wdio.conf.js file:

```
const wdioConf = require('terra-toolkit/lib/wdio/conf');
const localIP = require('ip');

const serverPort = 8080;

const config = {
  ...wdioConf.config,
  baseUrl: `http://${localIP.address()}:${serverPort}`,
  reporters: ['spec'],

  // Configuration for SeleniumDocker service
  seleniumDocker: {
    enabled: !process.env.CI,
    cleanup: true, 
    env: {
      TZ: 'America/Chicago'
    },
  },
};

exports.config = config;
```

**Comment by emilyrohrbough** [comment]
@k1nger Are you starting a docker container before attempting to run wdio?

**Comment by emilyrohrbough** [comment]
While digging through windows issues, @BenBoersma came across documentation that has indicated docker and virtual machines can have issues. Have you looked through this documentation regarding docker setup? https://docs.docker.com/docker-for-windows/install/

**Comment by k1nger** [comment]
Sorry, this got lost on me. My docker setup seems fine for other containers with no issues.

Further testing, I went into terra-toolkit and tried running docker-compose up against the docker-compose file and it failed to start. Adding an environment variable to my powershell 

`$Env:COMPOSE_CONVERT_WINDOWS_PATHS=1`

Helped fix the issue running docker-compose up. Still though receiving timeout issues when trying to execute test.

Also have had other engineers test this with same failures. As we are getting pretty deep into our development with this, I would be happy to provide as much help as needed or resources to help determine what is going on.

**Comment by k1nger** [comment]
Okay, maybe we can now mark this issue as closed.

Pulling the images helps for sure.

Secondly, windows firewall is probably the most annoying thing installed on my machine. It was blocking connections coming from DockerNAT for some reason so selenium couldn't reach the localhost instance of my app. 

Changing the firewall settings to allow the port to come through fixed my issue.

**Comment by bjankord** [comment]
Nice 👍

**Comment by k1nger** [comment]
The main issue is that dockernat is marked as public. So when node starts, if you don’t check public, private, anonymous checkboxes or whatever comes up from windows firewall, it’ll block.

Here’s a powershell script to mark dockernat as private which would fix the issue without having to change any firewall rules:

Set-NetConnectionProfile  -networkcategory private -InterfaceAlias "vEthernet (dockerNAT)"
